version: '3'

services:
  laravel-app:
    build: . 
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/
    networks:
      - app-network
    
  mysql-app:
    image: mysql:8.0.27
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: super_management_laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge