version: '3'

volumes:
  mysqlvolume:

networks:
  network:
    driver: bridge

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:80"
    working_dir: /usr/share/nginx/
    volumes:
      - ./:/usr/share/nginx/
    networks:
      - network

  database:
    container_name: database
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysqlvolume:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_DATABASE: super_management_laravel
      MYSQL_ROOT_PASSWORD: root
